name: star_wars
description: A Star Wars characters and movies listing app made with Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.4.3+7
  fluttermoji: ^1.0.0
  get: ^4.6.5
  http: ^0.13.5
  sqflite: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true